#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config external_bar all \
	window_border on \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.15 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	window_border_width 2 \
	window_border_hidpi off \
	window_border_radius 11 \
	window_animation_duration 0.22 \
	active_window_border_color 0xffBD93F9 \
	normal_window_border_color 0xff2a2f38 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 15 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 8

yabai -m config layout bsp

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

borders active_color=0xffbd93f9 inactive_color=0x00000000 width=2.0 &
