# set true color

# play nice with nvim when using alacritty
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# enable mouse
set -g mouse on

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# vim navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set -g @catppuccin_flavour 'mocha'

# plugins
set -g @plugin "nordtheme/tmux"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm';

# vi mode
set-window-option -g mode-keys vi

# open splits in current directory
bind v split-window -v -c "#{pane_current_path}"
bind s split-window -h -c "#{pane_current_path}"

bind-key C-r rotate-window

bind-key f resize-pane -Z

# Enable native Mac OS X copy/paste
set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

