import = ["/Users/enak/.config/dotfiles/alacritty/themes/dracula.toml"]

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetbrainsMono Nerd Font"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"

[font.italic]
family = "JetbrainsMono Nerd Font"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Full"
dynamic_title = true
dynamic_padding = true
